<?xml version = "1.0"  encoding = "utf-8"?>
<!DOCTYPE car_catalog [
<!ELEMENT car_catalog (car+)>
<!ELEMENT car (year, make, model, color, engine, number_of_doors, transmission_type, accessories)>
  <!ELEMENT make (#PCDATA)>
  <!ELEMENT model (#PCDATA)>
  <!ELEMENT year (#PCDATA)>
  <!ELEMENT color (#PCDATA)>
  <!ELEMENT engine (number_of_cylinders, fuel_system)>
  <!ELEMENT number_of_doors (#PCDATA)>
  <!ELEMENT transmission_type (#PCDATA)>
  <!ELEMENT accessories (#PCDATA)>
  <!ELEMENT number_of_cylinders (#PCDATA)>
  <!ELEMENT fuel_system (#PCDATA)>

  <!ATTLIST accessories radio CDATA #REQUIRED>
  <!ATTLIST accessories air_conditioning CDATA #REQUIRED>
  <!ATTLIST accessories power_windows CDATA #REQUIRED>
  <!ATTLIST accessories power_steering CDATA #REQUIRED>
  <!ATTLIST accessories power_brakes CDATA #REQUIRED>

  <!ENTITY c "Chevrolet">
  <!ENTITY f "Ford">
  <!ENTITY d "Dodge">
  <!ENTITY h "Honda">
  <!ENTITY n "Nisson">
  <!ENTITY t "Toyota">

]>

<?xml-stylesheet type="text/css" href="cars.css"?>
  <car_catalog>
    <car>
      <make> &c; </make>
      <year> 1987 </year>
      <model> imp </model>
      <color> grey </color>
      <engine>
        <number_of_cylinders> 9 cylinder
        </number_of_cylinders>
        <fuel_system> multi-port fuel injected </fuel_system>
      </engine>
      <number_of_doors> 6 door </number_of_doors>
      <transmission_type> 4 speed automatic......
      </transmission_type>
      <accessories radio = "yes"  air_conditioning = "yes"
                    power_windows = "yes"
                    power_steering = "yes"
                    power_brakes = "yes" />
    </car>
    
    <car>
      <make> &h; </make>
      <year> 2021</year>
      <model> vol </model>
      <color> Black </color>
      <engine>
        <number_of_cylinders> 6 cylinder
        </number_of_cylinders>
        <fuel_system> fuel injected </fuel_system>
      </engine>
      <number_of_doors> 4 door </number_of_doors>
      <transmission_type> 4 speed manual.... </transmission_type>
      <accessories radio = "yes"  air_conditioning = "yes"
                    power_windows = "no"  power_steering = "yes"
                    power_brakes = "yes" />
    </car>
  </car_catalog>