<?xml version = "1.0" encoding = "utf-8"?>
<!DOCTYPE car_catalog [
<!ELEMENT planes_for_sale (ad+)>
<!ELEMENT ad (year, make, model, color, description,
price?, seller, location)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT make (#PCDATA)>
<!ELEMENT model (#PCDATA)>
<!ELEMENT color (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT seller (#PCDATA)>
<!ELEMENT location (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT state (#PCDATA)>
<!ATTLIST seller phone CDATA #REQUIRED>
<!ATTLIST seller email CDATA #IMPLIED>
<!ENTITY c "Cessna">
<!ENTITY p "Piper">
<!ENTITY b "Beechcraft">
]>
<?xml-stylesheet type="text/css" href="planes.css"?>
<planes_for_sale>
	<ad>
		<make> &p; </make>
		<year> 1987 </year>
		<model> volvo </model>
		<color> grey </color>
		<description> xxxxxxxxxxxxxxxxxxxxxxxxxxx </description>
		<price> Rs.9,00,000 </price>
		<seller phone = "98181818526"> Skyway Aircraft </seller>
		<location>
			<city> Mangalore </city>
			<state> Karnataka </state>
		</location>
	</ad>
	<ad>
		<make> &c; </make>
		<year> 1988 </year>
		<model> Boeing </model>
		<color> blue</color>
		<description>yyyyyyyyyyyyyyyyyyyyyyy </description>
		<price> Rs. 80,000 </price>
		<seller phone = "7896523145" email = "boee@www.axl.com">boeee aicraft</seller>
		<location>
			<city> chennai </city>
			<state> tamilnadu</state>
		</location>
	</ad>
</planes_for_sale>